# Calibration file

Notebook used to compute the inter-prism and inter-GPS distance after an experiment, also their positions into a lidar frame if the measures were done.
Just the extrinsic calibration file is needed with the lidar height.

In [1]:
import sys
sys.path.append("../")
import numpy as np
import importlib
import scripts.theodolite_utils as theodo_u
import scripts.groundtruth_utils as theodo_g
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from scripts.theodolite_utils import read_file
from scripts.theodolite_utils import sensors_positions_lidar_frame

path_list = [
    # "../data/20230725-1/",
    # "../data/20230725-2/",
    # "../data/20230725-3/",
    "../data/20220224/",
    "../data/20220307/",
    # "../data/20220312/",
    "../data/20220314/",
    "../data/20220316/",
    # "../data/20220331-1/",
    # "../data/20220331-2/",
    # "../data/20220427-1/",
    # "../data/20220427-2/",
    # "../data/20220513-1/",
    # "../data/20220513-2/",
    # "../data/20220513-3/",
    # "../data/20220513-4/",
    # "../data/20220513-5/",
    # "../data/20220513-6/",
    "../data/20220525-1/",
    "../data/20220525-2/",
    "../data/20220622-1/",
    "../data/20220622-2/",
    "../data/20220630-1/",
    "../data/20220630-2/",
    # "../data/20220711-1/",
    "../data/20220711-1/",
    # "../data/20221103-1/",
    # "../data/20221103-2/",
    # "../data/20221103-3/",
    # "../data/20221109-1/",
    # "../data/20221109-2/",
    # "../data/20221109-3/",
    # "../data/20221110/",
    # "../data/20221116-1/",
    # "../data/20221123/",
    # "../data/20221124/",
    # "../data/20221129-1/",
    # "../data/20221129-2/",
    # "../data/20221129-3/",
    # "../data/20221129-4/",
    # "../data/20221129-5/",
    # "../data/20221205-1/",
    # "../data/20221205-2/",
    # "../data/20221205-3/"
]

In [2]:
# Warthog experiment
theodo_u = importlib.reload(theodo_u)
for i in path_list:
    print(i)
    theodo_u.read_calibration_gps_prism_lidar(i+"sensors_extrinsic_calibration/calibration_raw.csv", i+"sensors_extrinsic_calibration/calibration_results.csv", "Robosense_32")

../data/20220224/
Distance inter-prism [m]:  0.8873983869065535 0.8239492380516431 1.0373833738116685
Distance inter-GPS [m]:  0.780733617998497 0.8366106177748998 0.5178917909150109
Conversion done !
../data/20220307/
Distance inter-prism [m]:  0.8826453435444301 0.8219041060670618 1.0386237013977653
Distance inter-GPS [m]:  0.7781099344563802 0.8431026980109139 0.5157221841320069
Conversion done !
../data/20220314/
Distance inter-prism [m]:  0.88644321828893 0.8247745777909554 1.0375311538487895
Distance inter-GPS [m]:  0.7829081036179948 0.8424633975958637 0.5165807364575292
Conversion done !
../data/20220316/
Distance inter-prism [m]:  0.88644321828893 0.8247745777909554 1.0375311538487895
Distance inter-GPS [m]:  0.7829081036179948 0.8424633975958637 0.5165807364575292
Conversion done !
../data/20220525-1/
Distance inter-prism [m]:  0.9069738865416104 0.734951292757258 1.027486624635416
Distance inter-GPS [m]:  0.7922879928784302 0.8393905729950949 0.5168505712794828
Conversion do

In [3]:
# # Marmotte experiments
# theodo_u = importlib.reload(theodo_u)
# theodo_u.read_calibration_prism_lidar_marmotte(path+"sensors_extrinsic_calibration/calibration_raw.csv", path+"sensors_extrinsic_calibration/calibration_results.csv", "Velodyne")

In [3]:
# Sensor positions in theodolite frame
theodo_u = importlib.reload(theodo_u)
for i in path_list :
    print(i)
    theodo_u.read_sensor_positions(i+"sensors_extrinsic_calibration/calibration_raw.csv", i+"sensors_extrinsic_calibration/sensor_positions.csv", "Robosense_32")

../data/20220224/

Sensors coordinates in theodolite frame :
Prism 1: [ 3.28086714 -0.41369425 -0.03188872  1.        ]
Prism 2: [ 4.00750607e+00 -3.88578754e-05 -3.29144452e-01  1.00000000e+00]
Prism 3: [ 3.01181183  0.28835403 -0.36897892  1.        ]
GNSS 1: [ 2.98004774 -0.24952869 -0.68083765  1.        ]
GNSS 2: [ 3.75388227 -0.21129862 -0.58459026  1.        ]
GNSS 3: [ 3.61148597  0.28608001 -0.56114466  1.        ]

LiDAR center :
O: [ 3.00599541e+00  2.14692137e-04 -7.37808674e-01]
Ox: [ 3.98517233 -0.04605587 -0.93547405]
Oy: [ 3.06841678  0.99534594 -0.66153694]
Oz: [ 3.19916927 -0.08680737  0.23948914]
../data/20220307/

Sensors coordinates in theodolite frame :
Prism 1: [ 2.78395681 -0.75235665 -0.08227363  1.        ]
Prism 2: [ 3.59757529 -0.55468399 -0.36158222  1.        ]
Prism 3: [ 2.72084173e+00  3.69348364e-04 -4.06227964e-01  1.00000000e+00]
GNSS 1: [ 2.54427429 -0.50644668 -0.72279256  1.        ]
GNSS 2: [ 3.29508752 -0.68536252 -0.62418381  1.        ]
GNSS 3:

In [4]:
theodo_u = importlib.reload(theodo_u)
for i in path_list :
    print(i)
    file_sensor_positions = theodo_u.if_file_exist(i + "sensors_extrinsic_calibration/sensor_positions.csv",'')
    sensors = np.array(read_file(file_sensor_positions))
    T_matrix_lidar = sensors_positions_lidar_frame(sensors, i + "sensors_extrinsic_calibration/sensor_position_lidar_frame.csv")

../data/20220224/
Transformation matrix of theodolite to LiDAR frame :
 [[ 0.97917692 -0.04627056 -0.19766538 -3.08923062]
 [ 0.06242137  0.99513125  0.07627173 -0.13157804]
 [ 0.19317386 -0.08702206  0.97729782  0.14039775]
 [ 0.          0.          0.          1.        ]]

Sensors coordinates in LiDAR frame :
Prism 1: [ 0.14876391 -0.34089412  0.77901127  1.        ]
Prism 2: [0.89988908 0.09343287 0.5928744  1.        ]
Prism 3: [-0.08054194  0.31523081  0.33650562  1.        ]
GNSS 1: [-0.0251128  -0.24580185  0.07239843  1.        ]
GNSS 2: [ 0.71181441 -0.15211315  0.31261854  1.        ]
GNSS 3: [0.54473487 0.33574353 0.26474171 1.        ]
GNSS 3: [ 0.00000000e+00  0.00000000e+00 -1.11022302e-16  1.00000000e+00]
../data/20220307/
Transformation matrix of theodolite to LiDAR frame :
 [[-0.93451397  0.32693811 -0.14069507  2.43894113]
 [-0.31734711 -0.94435048 -0.08656205  0.51425742]
 [-0.16116589 -0.03624427  0.98626158  1.12912686]
 [ 0.          0.          0.          1.  

In [6]:
theodo_g = importlib.reload(theodo_g)
for i in path_list:
    print(i)
    theodo_g.read_sensor_positions_with_uncertainty(i+"sensors_extrinsic_calibration/calibration_raw.csv", i+"sensors_extrinsic_calibration/sensor_positions.csv", "Robosense_32")

../data/20230725-1/
Conversion done !
../data/20230725-2/
Conversion done !
../data/20230725-3/
Conversion done !


In [10]:
%matplotlib notebook
theodo_g = importlib.reload(theodo_g)
for i in path_list:
    sensors_lidar = np.array(read_file(i + "sensors_extrinsic_calibration/sensor_position_lidar_frame.csv"))
    P1_lidar, P2_lidar, P3_lidar, G1_lidar, G2_lidar, G3_lidar, O_lidar = sensors_lidar[:7]

    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")

    ax.scatter3D(P1_lidar[0], P1_lidar[1], P1_lidar[2], color="red", label="P1_lidar")
    ax.scatter3D(P2_lidar[0], P2_lidar[1], P2_lidar[2], color="blue", label="P2_lidar")
    ax.scatter3D(P3_lidar[0], P3_lidar[1], P3_lidar[2], color="green", label="P3_lidar")
    ax.scatter3D(O_lidar[0], O_lidar[1], O_lidar[2], color="yellow", label="O")


    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    ax.set_aspect("equal")

    ax.legend()

    plt.show()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>